version: 2
updates:
#######################################################
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@autoview/*"
      - dependency-name: "typia"
      - dependency-name: "typescript"
      - dependency-name: "ts-patch"
    groups:
      AutoView:
        patterns:
          - "@autoview/*"
          - "typia"
      NestJS:
        patterns:
          - "@nestjs/*"
      TypeScript:
        patterns:
          - "typescript"
          - "ts-node"
          - "ts-patch"